### ISSUE TITLE
Exercise 14 download parquet link not working

### ISSUE THREAD

**Issue by alejandrobalderas** [udacity/nd0821-c2-build-model-workflow-exercises#2]
I was getting this error when running the Exercise 14 pipeline. This came in the preprocessing step.

OSError: Could not open parquet input source '<Buffer>': Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

Looking into it I saw that the data was not being downloaded correctly. Moreover the link actually returns a 404 error.

Link in the config.yaml
https://raw.githubusercontent.com/udacity/nd0821-c2-build-model-workflow/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?token=ABNEVO6ANSAW5NZCIJ5ZXV3AOVMZK

Changing it to the following link seems to solve this issue
https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true

**Comment by mvirgo** [comment]
Nice catch - just fixed with d17fd61
